# This service file is used to attach a 
# stream consumer to the camera system
# the output stream won't be synchronized

# Full path to the device to attach, i.e /dev/video0
string camera_device_path 

# Full path to the output stream device, i.e rtp://192.168.0.65:5000
string output_stream_path 
---
bool succeeded